### ISSUE TITLE
#2405 Nom de taches inconnues

### ISSUE THREAD

**Issue by lmag** [Eoxia/task-manager#36]
Nombre de tache inconnues on est obligé d'ouvrir la tache (option ouvrir par défaut ?)

**Comment by nicolas-eoxia** [comment]
Activer l'option "Display project and task pour avoir un affichage plus complet.
![image](https://user-images.githubusercontent.com/52404047/76070650-2b555580-5f95-11ea-845c-67ce837e7628.png)

Avec l'option activer dans le profil Utilisateur.
![image](https://user-images.githubusercontent.com/52404047/76070517-f8ab5d00-5f94-11ea-806e-3479841e8813.png)

**Comment by eoxia-jimmy** [comment]
Bonjour,

Pouvons nous fermer cette issue ?
